spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jahcloud?createDatabaseIfNotExist=true
    username: testuser
    password: batata
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always
      #schema-locations: classpath:schema-test.sql
      data-locations: classpath:test-data.sql
  logging:
    level:
      root: DEBUG
      org.springframework: DEBUG
      org.hibernate: DEBUG
app:
  jwtSecret: c2VjdXJlS2V5MjAyMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMA==
  jwtExpirationMs: 900000

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  packages-to-scan: com.c0lap5o.JahCloud.controller
